Update Dockerfile.Windows-CY2024
Signed-off-by: Cédrik Fuoco <105517825+cedrik-fuoco-adsk@users.noreply.github.com>

diff --git a/dockerfiles/Dockerfile.Windows-CY2024 b/dockerfiles/Dockerfile.Windows-CY2024
--- a/dockerfiles/Dockerfile.Windows-CY2024
+++ b/dockerfiles/Dockerfile.Windows-CY2024
@@ -51,13 +51,30 @@ RUN choco install strawberryperl -y
 
 # Download and install MSYS2
 RUN $url = 'https://github.com/msys2/msys2-installer/releases/download/2023-05-26/msys2-x86_64-20230526.exe'; `
+    Write-Host "Downloading MSYS2..."; `
     Invoke-WebRequest -Uri $url -OutFile 'msys2-installer.exe'; `
-    Start-Process -FilePath 'msys2-installer.exe' -ArgumentList 'in', '--confirm-command', '--accept-messages', '--root', 'C:\msys64' -Wait; `
-    Remove-Item 'msys2-installer.exe'
+    Write-Host "Installing MSYS2..."; `
+    Start-Process -FilePath 'msys2-installer.exe' -ArgumentList 'in', '--confirm-command', '--accept-messages', '--root', 'C:\msys64' -Wait -NoNewWindow; `
+    Remove-Item 'msys2-installer.exe'; `
+    Write-Host "MSYS2 installation completed."
+
+# Add MSYS2 to PATH and verify installation
+RUN $env:PATH = "C:\msys64\usr\bin;C:\msys64\mingw64\bin;$env:PATH"; `
+    [Environment]::SetEnvironmentVariable('PATH', $env:PATH, [EnvironmentVariableTarget]::Machine); `
+    Write-Host "Verifying MSYS2 installation..."; `
+    if (Test-Path 'C:\msys64\usr\bin\bash.exe') { `
+        Write-Host "MSYS2 bash found at C:\msys64\usr\bin\bash.exe"; `
+    } else { `
+        Write-Error "MSYS2 bash not found!"; `
+        exit 1; `
+    }
 
 # Update MSYS2 and install required packages
-RUN & 'C:\msys64\usr\bin\bash.exe' -l -c 'pacman -Syu --noconfirm'; `
-    & 'C:\msys64\usr\bin\bash.exe' -l -c 'pacman -S --noconfirm mingw-w64-x86_64-autotools mingw-w64-x86_64-cmake mingw-w64-x86_64-cmake-cmcldeps mingw-w64-x86_64-glew mingw-w64-x86_64-libarchive mingw-w64-x86_64-make mingw-w64-x86_64-meson mingw-w64-x86_64-toolchain autoconf automake bison flex git libtool nasm p7zip patch unzip zip'
+RUN Write-Host "Updating MSYS2..."; `
+    $env:PATH = "C:\msys64\usr\bin;C:\msys64\mingw64\bin;$env:PATH"; `
+    Start-Process -FilePath "C:\msys64\usr\bin\bash.exe" -ArgumentList '-l', '-c', "'pacman -Syu --noconfirm'" -Wait -NoNewWindow; `
+    Write-Host "Installing MSYS2 packages..."; `
+    Start-Process -FilePath "C:\msys64\usr\bin\bash.exe" -ArgumentList '-l', '-c', "'pacman -S --noconfirm mingw-w64-x86_64-autotools mingw-w64-x86_64-cmake mingw-w64-x86_64-cmake-cmcldeps mingw-w64-x86_64-glew mingw-w64-x86_64-libarchive mingw-w64-x86_64-make mingw-w64-x86_64-meson mingw-w64-x86_64-toolchain autoconf automake bison flex git libtool nasm p7zip patch unzip zip'" -Wait -NoNewWindow
 
 # Install aqt (Qt installer tool) via pip
 RUN & 'C:\Python310\python.exe' -m pip install --upgrade pip; `
